### ISSUE TITLE
Tracebacks when having diff prefixes off.

### ISSUE THREAD

**Issue by davidalmgren** [kimgr/git-format#3]
When having set

git config --global diff.noprefix false

running git format --amend for example causes a traceback because it's trying to remove the a/ or b/ prefixes.

**Comment by kimgr** [comment]
@Davalm14 Thanks! I'm thinking something like: https://github.com/kimgr/git-format/pull/4

**Comment by kimgr** [comment]
#4 merged, thanks for the report!
